version: '3.1'

services:
  springboot:
    build: .
    # image: registry.gitlab.com/idgst/springboot-mongo-demo:latest
    restart: always
    container_name: mail-service
    ports:
      - 8182:8080
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: springboot-mongo
#    ports:  # for demo/debug purpose only
#      - 27018:27017
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always