version: '3.1'

services:
  audit-service:
    #build: .
    image: audit-service:latest
    restart: always
    container_name: audit-service
    working_dir: /opt/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: audit-service-db
#    ports:  # for demo/debug purpose only
#      - 27018:27017
    volumes:
      - $HOME/data/audit-service-db-data:/data/db
      - $HOME/data/audit-service-db-bkp:/data/bkp
    restart: always